apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/todd-tran888/argo-cd' # Update to match your fork.
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: microk8s # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
